### ISSUE TITLE
Labels in Washington, D.C. are missing the "D.C."

### ISSUE THREAD

**Issue by orangejulius** [pelias/labels#14]
All addresses and venues in Washington, D.C. appear to have labels generated that end with simply "Washington, USA". This is pretty confusing since the D.C. is what everyone uses to distinguish the country's capital from the state of Washington.

[1600 Pennyslvania Ave](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=1600%20pennsylvania%20ave%20nw,%20washington%20DC)
![screenshot from 2017-02-27 14-58-00](https://cloud.githubusercontent.com/assets/111716/23377237/3b19da98-fcfd-11e6-971d-fb5afd738ee2.png)

[National Air and Space Museum](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=national%20air%20and%20space%20museum,%20washington%20DC)
![screenshot from 2017-02-27 14-59-44](https://cloud.githubusercontent.com/assets/111716/23377282/6df7c0a6-fcfd-11e6-971f-b2dce2db07cc.png)

[Busboys and Poets, Washington DC](http://pelias.github.io/compare/#/v1/autocomplete%3Ftext=busboys%20and%20poets,%20washington%20DC)
![screenshot from 2017-02-27 15-04-40](https://cloud.githubusercontent.com/assets/111716/23377446/1354d11a-fcfe-11e6-8289-cc18c3384216.png)

**Comment by trescube** [comment]
related to pelias/pelias#509

**Comment by orangejulius** [comment]
![Screenshot_2019-05-15_08-12-42](https://user-images.githubusercontent.com/111716/57774705-39c24000-76e9-11e9-950e-f531a6a19c08.png)
This is fixed! 

It's likely been fixed for a long time, as better data made its way into WOF, especially regarding abbreviations.
