### ISSUE TITLE
Parse order on the label field for Portugal

### ISSUE THREAD

**Issue by npatroni** [pelias/labels#29]
Hi,

i'm new to Pelias and i need help to understand how to change label field order.

For Portugal we use the street name flowed by the house number (and then the rest of the fields). 

How is this configured in pelias ?

TIA
Nuno

**Comment by missinglink** [comment]
Hi @npatroni, the configuration is in https://github.com/pelias/api/blob/master/middleware/localNamingConventions.js#L5

We would be happy to accept a PR for this change for Portugal.

There should be a corresponding test case in the tests directory you can use to confirm the change via `npm test`

**Comment by npatroni** [comment]
Thanks, 

What do I need to do to request this change?

Regards
Nuno

**Comment by missinglink** [comment]
Resolved via https://github.com/pelias/api/pull/1199
