### ISSUE TITLE
default name / label

### ISSUE THREAD

**Issue by stefanocudini** [pelias/labels#32]
actually is configurable by _pelias.json_ the default structure of address string? for the fields label,name
now is:
> "housenumber street"

I seen that the data imported in ealsticseach having this structure, but I need of reverse order..
> "street housenumber" 
mainly I need this in the pelias/api results... in label fields!

**Comment by missinglink** [comment]
@stefanocudini this issue may have been resolved by https://github.com/pelias/api/pull/1344?

**Comment by stefanocudini** [comment]
I'm sorry @missinglink  I find myself in a situation of health problems, I hope to return soon to work on this.
bye

**Comment by orangejulius** [comment]
I think as mentioned this has been solved by https://github.com/pelias/api/pull/1344. We don't have any plans to make label generation configurable through `pelias.json`, but if there are any ways in general we can improve labels, let us know.
