### ISSUE TITLE
Label missing admin part

### ISSUE THREAD

**Issue by laszbalo** [pelias/labels#33]
Should one here not pass in record.*parent*.country_a?
https://github.com/pelias/labels/blob/master/labelGenerator.js#L148

Similarily, when building the admin part, should it not be record.*parent*?
https://github.com/pelias/labels/blob/master/labelGenerator.js#L153

**Comment by orangejulius** [comment]
Hi @laszbalo,
I don't believe so. The API middleware has several stages, one of which ([geojsonify](https://github.com/pelias/api/blob/master/routes/v1.js#L62)), runs before the [assignLabels](https://github.com/pelias/api/blob/master/routes/v1.js#L66) middlelware and creates the top level properties `country_a` (and others) for use in the final response object. The labels are created using those.

https://github.com/pelias/api/blob/e04a6b22052d6c21d5865e14b80c7be09612a1dc/routes/v1.js#L62-L63

Is there a particular issue or concern you're looking to address?

**Comment by laszbalo** [comment]
Thanks for the info. Not really, I am just trying to use the `pelias-whosonfirst` importer and the `pelias-labels` projects to generate labels in my own code, but I missed the fact that the pelias documents are needed post-processing before I can feed them into `pelias-labels`.
